library(data.table)
library(tidyr)
power <- fread("household_power_consumption.txt")
power_sub <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
power_sub <- as.data.frame(power_sub)
power_sub <- unite(power_sub, Date_Time, Date, Time, sep = " ")
power_sub$Global_active_power <- as.numeric(power_sub$Global_active_power)
power_sub$Date_Time <- strptime(power_sub$Date_Time, format ="%e/%m/%Y %H:%M:%S")

png("plot3.png", 480, 480, "px")
plot(power_sub$Date_Time, power_sub$Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering')
lines(power_sub$Date_Time, power_sub$Sub_metering_2, col = 'red')
lines(power_sub$Date_Time, power_sub$Sub_metering_3, col = 'blue')
legend("topright",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black", "red", "blue"))

dev.off()
